build-job:
  tags: 
    - testing
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pwd
    - git clone "https://Farid:farid1244@gitlab.homayoonsadeghi.com/spiderify/spiderify-backend.git"
    - cd spiderify-backend
    - git checkout develope


test-job1:
  stage: test
  tags: 
    - testing
  script:
    - echo "This job tests something"



deploy-prod:
  stage: deploy
  tags: 
    - testing
  script:
    - pwd
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - ls
    - python3 .\crawler\AmScrapper.py
