build-job:
  tags:
    - testing
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pwd
    - git clone --branch develope "https://Farid:farid1244@gitlab.homayoonsadeghi.com/spiderify/spiderify-backend.git"
    - cd spiderify-backend
    # - apt-get install python3.8-env
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - export PATH="$PATH:$HOME/.poetry/bin/"
    - source $HOME/.poetry/env
    - poetry install
    - source `poetry env info --path`/bin/activate

test-job1:
  stage: test
  tags:
    - testing
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  tags:
    - testing
  only:
    - develope
  script:
    - pwd
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - ls

    - python3 crawler/AmScrapper.py
