build-job:
  tags:
    - testing
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pwd
    - git clone --branch develope "https://Farid:farid1244@gitlab.homayoonsadeghi.com/spiderify/spiderify-backend.git"
    - cd spiderify-backend
    - python3 -m venv env
    - ls
    - poetry install
    - source env/bin/activate
  artifacts:
    paths:
      - env/
    # - apt-get install python3.8-env

test-job1:
  stage: test
  tags:
    - testing
  script:
    - echo "This job tests something"
  artifacts:
    paths:
      - env/

deploy-prod:
  stage: deploy
  tags:
    - testing
  only:
    - develope
  script:
    - pwd
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - ls
    - python3 crawler/AmScrapper.py
