build-job:
  tags: testing
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - git clone "https://gitlab.homayoonsadeghi.com/spiderify/spiderify-backend.git"
    - cd spiderify-backend
    - git switch develope


test-job1:
  stage: test
  tags: testing
  script:
    - echo "This job tests something"



deploy-prod:
  stage: deploy
  tags: testing
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - python3 .\crawler\AmScrapper.py
