version: '3.7'

services:
  db:
    restart: on-failure
    image: mysql:8.0
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        FLASK_ENV: development
    image: spiderify-api:local
    container_name: spiderify-api
    tty: true
    stdin_open: true
    command: ["python3", "app.py"]
    ports:
      - "8080:8080"
    volumes:
      - "./common/sentiment_model/1:/app/common/sentiment_model/1:ro"
    depends_on:
      - db
  sentiment:
    restart: unless-stopped
    image: tensorflow/serving:latest
    container_name: sentiment
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - "./common/sentiment_model:/models/sentiment:ro"
    env_file:
      - .env
    environment:
      MODEL_NAME: ${MODEL_NAME}


volumes:
  db-data:
    driver: local
    name: db-data
    external: false

