# Before Start This File Use These Commands:
# docker network create --driver bridge external-network
version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    profiles:
      - all
      - full
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin -h 'localhost' -u root -p${DB_PASSWORD} ping --silent"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - "db-data:/var/lib/mysql"
      - "./mysql/scripts:/docker-entrypoint-initdb.d/:ro"
      - "./mysql/conf.d:/etc/mysql/conf.d:ro"
    networks:
      - app-network

  redis:
    container_name: redis
    image: "redis:6.2-bullseye"
    restart: on-failure
    profiles:
      - all
      - full
    environment:
      - TZ="Asia/Tehran"
      - REDIS_PASSWORD=ubuntu
      - REDIS_REPLICATION_MODE=master
    command: ["--save 10 100", "--requirepass ubuntu"]
    mem_limit: 4G
    memswap_limit: 4G
    mem_reservation: 3G
    mem_swappiness: 0
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - "redis-data:/data"
    depends_on:
      - mysql
    networks:
      - app-network

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    restart: unless-stopped
    profiles:
      - all
      - full
    ports:
      - "8001:8001"
    volumes:
      - "redisinsight-data:/db"
    depends_on:
      - redis
    networks:
      - app-network

  spiderify-api:
    image: spiderify-api:${TAG:-local}
    container_name: spiderify-api
    restart: unless-stopped
    profiles:
      - all
    env_file:
      - .env
    command:
      [
        "gunicorn",
        "manage:app",
        "--bind=0.0.0.0:8080",
        "--workers=4",
        "--threads=4",
        "--timeout=600",
        "--worker-class=gevent",
        "--worker-connections=1000"
      ]
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  sentiment-api:
    image: tensorflow/serving:latest
    container_name: sentiment-api
    restart: unless-stopped
    profiles:
      - all
    cpu_count: 3
    mem_limit: 4G
    memswap_limit: 4G
    mem_reservation: 3G
    mem_swappiness: 0
    environment:
      MODEL_NAME: sentiment
    volumes:
      - "./common/sentiment_model:/models/sentiment:ro"
    depends_on:
      - spiderify-api
      - mysql
    networks:
      - app-network

  summarization-api:
    image: summarization:${TAG:-local}
    container_name: summarization-api
    restart: unless-stopped
    profiles:
      - all
    cpu_count: 3
    mem_limit: 6G
    memswap_limit: 6G
    mem_reservation: 4G
    mem_swappiness: 0
    command:
      [
        "uvicorn",
        "api:app",
        "--workers",
        "2",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    volumes:
      - "/home/tesla/Project/SpideriFy/spiderify-summarization/model:/home/appuser/model:ro"
    depends_on:
      - spiderify-api
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:${TAG:-local}
    container_name: nginx
    restart: unless-stopped
    profiles:
      - all
      - full
    ports:
      - "80:80"
    depends_on:
      - spiderify-api
    networks:
      - app-network
      - external-network

networks:
  app-network:
    external: false
  external-network:
    external: true

volumes:
  db-data:
    name: db_data
    driver: local-persist
    driver_opts:
      mountpoint: "/var/spiderify-db/mysql/"
  redis-data:
    name: redis_data
    driver: local-persist
    driver_opts:
      mountpoint: "/var/spiderify-db/redis/"
  redisinsight-data:
    name: redisinsight_data
    driver: local-persist
    driver_opts:
      mountpoint: "/var/spiderify-db/redisinsight/"
