version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    env_file:
      - .docker-compose.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -p${ROOT_PASS} ping --silent"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - "db-data:/var/lib/mysql"
      - "./mysql/scripts:/docker-entrypoint-initdb.d/:ro"
      - "./mysql/conf.d:/etc/mysql/conf.d:ro"

  spiderify-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        FLASK_ENV: production
    image: spiderify-api:${TAG:-local}
    container_name: spiderify-api
    restart: unless-stopped
    command: ["python3", "app.py"]
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  sentiment-api:
    image: tensorflow/serving:latest
    container_name: sentiment-api
    restart: unless-stopped
    environment:
      MODEL_NAME: sentiment
    volumes:
      - "./common/sentiment_model:/models/sentiment:ro"
    deends_on:
      - spiderify-api
      - mysql

  summarization-api:
    image: summarization:${TAG:-local}
    container_name: summarization-api
    restart: unless-stopped
    command: ["uvicorn", "api:app", "--workers", "2", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - "/home/tesla/Project/SpideriFy/spiderify-summarization/model:/home/appuser/model:ro"
    depends_on:
      - spiderify-api
      - mysql

volumes:
  db-data:
    name: db_data
    driver: local-persist
    driver_opts:
      mountpoint: "/var/spiderify-db/mysql/"
